# Generated by Django 4.0.3 on 2022-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombre y apellido')),
                ('dni', models.CharField(max_length=8, verbose_name='Número de DNI')),
                ('telefono', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=200)),
            ],
        ),
    ]
