# Generated by Django 4.0.3 on 2022-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='curso',
            field=models.CharField(default=' ', max_length=10, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='principal',
            name='correo_electronico',
            field=models.CharField(max_length=200, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='telefono',
            field=models.CharField(max_length=100, verbose_name='teléfono'),
        ),
    ]
